// Native (desktop, no ESP32 needed) test for wyzesense_protocol.cpp.
// Encodes each command and compares byte-for-byte against reference hex
// dumps captured directly from the real `wyzesense` Python library running
// against this exact protocol -- generated by a script, never hand-typed,
// to remove any chance of transcription error. See the session for how
// these were captured (monkeypatched os.write() around Packet.Send()).

#include <cstdio>
#include <cstring>
#include <string>
#include "../lib/wyzesense_protocol/wyzesense_protocol.h"

using namespace wyzesense;

static int g_failures = 0;

static std::string ToHex(const uint8_t *data, size_t len) {
  static const char *hexch = "0123456789abcdef";
  std::string s;
  s.reserve(len * 2);
  for (size_t i = 0; i < len; i++) {
    s.push_back(hexch[data[i] >> 4]);
    s.push_back(hexch[data[i] & 0xF]);
  }
  return s;
}

static void CheckEncode(const char *name, const Packet &p, const char *expectedHex) {
  uint8_t buf[128];
  size_t n = p.Encode(buf, sizeof(buf));
  std::string got = ToHex(buf, n);
  if (got == expectedHex) {
    printf("PASS  %-20s %s\n", name, got.c_str());
  } else {
    printf("FAIL  %-20s got=%s expected=%s\n", name, got.c_str(), expectedHex);
    g_failures++;
  }
}

static void Check(const char *name, bool cond, const std::string &detail = "") {
  if (cond) {
    printf("PASS  %-20s %s\n", name, detail.c_str());
  } else {
    printf("FAIL  %-20s %s\n", name, detail.c_str());
    g_failures++;
  }
}

static std::vector<uint8_t> FromHex(const std::string &hex) {
  std::vector<uint8_t> out;
  for (size_t i = 0; i + 1 < hex.size(); i += 2) {
    out.push_back(uint8_t(strtol(hex.substr(i, 2).c_str(), nullptr, 16)));
  }
  return out;
}

int main() {
  uint8_t enrR[16];
  memset(enrR, '0', 16);

  const char mac[8] = {'E', 'F', '0', '2', 'F', 'F', '4', '9'};
  const uint8_t r1[16] = {'O', 'k', '5', 'H', 'P', 'N', 'Q', '4',
                           'l', 'f', '7', '7', 'u', '7', '5', '4'};

  CheckEncode("Inquiry", MakeInquiry(), "aa55430327016c");
  CheckEncode("GetMAC", MakeGetMAC(), "aa554303040149");
  CheckEncode("GetVersion", MakeGetVersion(), "aa55530316016b");
  CheckEncode("GetKey", MakeGetKey(), "aa55430306014b");
  CheckEncode("EnableScan", MakeEnableScan(), "aa5553041c010173");
  CheckEncode("DisableScan", MakeDisableScan(), "aa5553041c000172");
  CheckEncode("FinishAuth", MakeFinishAuth(), "aa55530414ff0269");
  CheckEncode("GetEnr", MakeGetEnr(enrR), "aa55431302303030303030303030303030303030300457");
  CheckEncode("GetSensorR1", MakeGetSensorR1(mac, r1), "aa55531b2145463032464634394f6b3548504e51346c663737753735340823");
  CheckEncode("VerifySensor", MakeVerifySensor(mac), "aa55530d234546303246463439ff04046b");
  CheckEncode("DelSensor", MakeDelSensor(mac), "aa55530b2545463032464634390368");
  CheckEncode("GetSensorList3", MakeGetSensorList(3), "aa55530430030189");
  CheckEncode("AsyncAckAlarm", MakeAsyncAck(NOTIFY_SENSOR_ALARM), "aa555319ff026a");

  if (g_failures == 0) {
    printf("\nAll encode tests passed.\n");
  } else {
    printf("\n%d encode test(s) FAILED.\n", g_failures);
  }
  return g_failures == 0 ? 0 : 1;
}
